### ISSUE TITLE
(Bug) Strange behavior of ¨ character in credits sequence

### ISSUE THREAD

**Issue by gensakudan** [maxim-zhao/psrp#81]
The `¨` character, which is used to denote the two dots above umlauted vowels, behaves strangely in the following ways:
- The game ignores any further lines of credit on a given screen if they follow a line that contains the character.
- If a line contains more than one such character, it seems to print other characters that it shouldn't, such as the `F` in the following screenshot:
![image](https://user-images.githubusercontent.com/90138378/176219281-dd0aefe8-179d-40e1-8f9e-d1386d7d7771.png)

Is this an issue with the fact that a unicode character is used or is it something else?

**Comment by maxim-zhao** [comment]
It's most likely a bug in the implementation. The Unicode should be mapped as a sequence of UTF-8 bytes to a single byte in ROM, leaving no scope for confusion.

**Comment by maxim-zhao** [comment]
This is a glitch caused by the use of ¨ which is two bytes when encoded as UTF-8; the code is using the byte length instead of the character length, so the decoder gets misaligned and bad things happen. I've fixed it by adding more load on the assembler to compute the final length of each text span at link time.
